[program:merkley-storefront]
command=/home/frappe/.local/bin/node /home/frappe/merkley-storefront-dev/app/node_modules/.bin/next start
directory=/home/frappe/merkley-storefront-dev/app
environment=PORT="3100",NODE_ENV="production"
user=frappe
autostart=true
autorestart=true
priority=5
stdout_logfile=/home/frappe/merkley-storefront-dev/logs/storefront.log
stderr_logfile=/home/frappe/merkley-storefront-dev/logs/storefront.error.log
stopwaitsecs=10
killasgroup=true
startretries=5
